[project]
name = "calculator-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.5.1",
    "mcp>=1.9.1",
    "numpy>=2.2.6",
    "scipy>=1.15.3",
    "sympy>=1.14.0",
]
